# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2020-04-10 05:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organation', '0002_courseorg_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='work_postion',
            new_name='work_position',
        ),
    ]
