# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2020-04-15 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organation', '0003_auto_20200410_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='images',
            field=models.ImageField(max_length=300, upload_to='teacher/%Y/%m', verbose_name='头像'),
        ),
    ]
