# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2020-04-15 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organation', '0004_auto_20200415_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseorg',
            name='images',
            field=models.ImageField(upload_to='org/%Y/%m', verbose_name='机构头像'),
        ),
    ]
